version: '3'
services:

    db:
        image: mongo:latest

        volumes:
            - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=user
            
